name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout terraform code"
        uses: actions/checkout@v4
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::211125437730:role/staging-oidc-policy
      - name: "Test workflow"
        run: echo "${{github.actor}} is testing this workflow."
      - name: "Testing STS"
        run: aws sts get-caller-identity
