name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout terraform code"
        uses: actions/checkout@v4

      - name: "Test workflow"
        run: echo "${{github.actor}} is testing this workflow."
